# Generated by Django 5.1.4 on 2025-06-10 11:05

import app_files.models
import app_files.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SecureFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dtm_created", models.DateTimeField(auto_now_add=True)),
                ("dtm_updated", models.DateTimeField(auto_now=True)),
                ("slug", models.CharField(max_length=12, unique=True)),
                (
                    "file",
                    models.FileField(
                        storage=app_files.storage.SecureFileStorage,
                        upload_to=app_files.models.get_file_path,
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                ("content_type", models.CharField(max_length=100)),
                ("file_size", models.BigIntegerField()),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Secure File",
                "verbose_name_plural": "Secure Files",
                "ordering": ["-dtm_created"],
            },
        ),
    ]
